//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionProyectosB.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProyectoUsuarios
    {
        public int ProyectoUsuarioId { get; set; }
        public int ProyectoId { get; set; }
        public int UsuarioId { get; set; }
    
        public virtual Proyectos Proyectos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
